In [14]:
import pandas as pd

data = """Название,Автор,Год издания,Цена
Преступление и наказание,Фёдор Достоевский,1866,450
Мастер и Маргарита,Михаил Булгаков,1967,520
Искусство легких касаний,Виктор Пелевин,2019,650
1984,Джордж Оруэлл,1949,380
Внутри убийцы,Майк Омер,2018,490
Тревожные люди,Фредрик Бакман,2019,580
"""

with open('books.csv', 'w', encoding='utf-8') as f:
    f.write(data)

print('Файл books.csv создан.')

Файл books.csv создан.

In [11]:
df = pd.read_csv('books.csv')
print("Весь DataFrame:")
display(df)

Весь DataFrame:

                   Название              Автор  Год издания  Цена
0  Преступление и наказание  Фёдор Достоевский         1866   450
1        Мастер и Маргарита    Михаил Булгаков         1967   520
2  Искусство легких касаний     Виктор Пелевин         2019   650
3                      1984      Джордж Оруэлл         1949   380
4             Внутри убийцы          Майк Омер         2018   490
5            Тревожные люди     Фредрик Бакман         2019   580

In [12]:
recent_books = df[df['Год издания'] > 2015]
print("\nКниги, изданные после 2015 года:")
display(recent_books)

Книги, изданные после 2015 года:

                   Название           Автор  Год издания  Цена
2  Искусство легких касаний  Виктор Пелевин         2019   650
4             Внутри убийцы       Майк Омер         2018   490
5            Тревожные люди  Фредрик Бакман         2019   580

In [13]:
sorted_df = df.sort_values(by='Цена', ascending=True)
print("\nОтсортированный по цене DataFrame:")
display(sorted_df)

Отсортированный по цене DataFrame:

                   Название              Автор  Год издания  Цена
3                      1984      Джордж Оруэлл         1949   380
0  Преступление и наказание  Фёдор Достоевский         1866   450
4             Внутри убийцы          Майк Омер         2018   490
1        Мастер и Маргарита    Михаил Булгаков         1967   520
5            Тревожные люди     Фредрик Бакман         2019   580
2  Искусство легких касаний     Виктор Пелевин         2019   650