In [34]:
import pandas as pd

In [35]:
data_food = {
    "Продукт": ["Курица", "Лосось", "Орехи", "Яблоко", "Банан", "Шоколад", "Творог", "Сыр", "Огурец", "Говядина"],
    "Категория": ["Мясо", "Рыба", "Снеки", "Фрукты", "Фрукты", "Снеки", "Молочные", "Молочные", "Овощи", "Мясо"],
    "Калории": [165, 208, 600, 52, 89, 540, 150, 400, 15, 250],
    "Белки": [31, 20, 15, 0.3, 1.1, 5, 18, 25, 0.8, 26]
}

food_df = pd.DataFrame(data_food)
display(food_df)

    Продукт Категория  Калории  Белки
0    Курица      Мясо      165   31.0
1    Лосось      Рыба      208   20.0
2     Орехи     Снеки      600   15.0
3    Яблоко    Фрукты       52    0.3
4     Банан    Фрукты       89    1.1
5   Шоколад     Снеки      540    5.0
6    Творог  Молочные      150   18.0
7       Сыр  Молочные      400   25.0
8    Огурец     Овощи       15    0.8
9  Говядина      Мясо      250   26.0

In [36]:
# Продукты с калорийностью выше 300
high_cal = food_df[food_df["Калории"] > 300]
print("Продукты с калорийностью > 300:")
display(high_cal)

Продукты с калорийностью > 300:

   Продукт Категория  Калории  Белки
2    Орехи     Снеки      600   15.0
5  Шоколад     Снеки      540    5.0
7      Сыр  Молочные      400   25.0

In [37]:
# Среднее количество белков по категориям
avg_protein = food_df.groupby("Категория")["Белки"].mean()
print("Среднее количество белков по категориям:")
print(avg_protein)

Среднее количество белков по категориям:
Категория
Молочные    21.5
Мясо        28.5
Овощи        0.8
Рыба        20.0
Снеки       10.0
Фрукты       0.7
Name: Белки, dtype: float64

In [38]:
# Сортировка по калорийности в порядке убывания
sorted_food = food_df.sort_values(by="Калории", ascending=False)
print("Отсортированный DataFrame:")
display(sorted_food)

Отсортированный DataFrame:

    Продукт Категория  Калории  Белки
2     Орехи     Снеки      600   15.0
5   Шоколад     Снеки      540    5.0
7       Сыр  Молочные      400   25.0
9  Говядина      Мясо      250   26.0
1    Лосось      Рыба      208   20.0
0    Курица      Мясо      165   31.0
6    Творог  Молочные      150   18.0
4     Банан    Фрукты       89    1.1
3    Яблоко    Фрукты       52    0.3
8    Огурец     Овощи       15    0.8